version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:82"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - svm_flask_app
      - vgg_flask_app

  svm_flask_app:
    build:
      context: ./services/svm_service
    ports:
      - "5000:5000"
    volumes:
      - ./services/svm_service/models/svm_model.pkl:/app/svm_model.pkl
    environment:
      - MODEL_PATH=/app/genre_model.pkl
      
  vgg_flask_app:
    build:
      context: ./services/vgg_service
    ports:
      - "5001:5001"
    volumes:
      - ./services/vgg_service/models/vgg_model.h5:/app/vgg_model.h5
    environment:
      - MODEL_PATH=/app/vgg_model.h5